# Metricbeat Configuration for Windows
# Collects system and application metrics

#========================== Modules configuration ============================
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

#========================== Metricbeat autodiscover ==============================
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#==========================  Modules configuration =============================
metricbeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - socket_summary  # Socket summary
    - core           # Per CPU core usage
    - diskio         # Disk IO
    - filesystem     # File system usage
    - fsstat         # File system summary
    - raid           # Raid
    - socket         # Sockets and connection info (linux only)
    - service        # systemd service status
  enabled: true
  period: 10s
  processes: ['.*']
  cpu.metrics:  [percentages, normalized_percentages]
  core.metrics: [percentages]

#------------------------------- Windows Module ------------------------------
- module: windows
  metricsets: ["perfmon"]
  enabled: true
  period: 10s
  perfmon.counters:
    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.time.total.pct
      query: '\Processor Information(_Total)\% Processor Time'
    - instance_label: memory.page_faults
      measurement_label: memory.page_faults.rate
      query: '\Memory\Page Faults/sec'

#================================ General =====================================
# Name of the shipper
name: "windows-metrics-${HOSTNAME}"

# Tags to include in each event
tags: ["windows", "metrics", "production"]

#================================ Outputs =====================================

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "changeme"
  index: "metricbeat-windows-%{+yyyy.MM.dd}"

#-------------------------- Logstash output --------------------------------
# Uncomment to use Logstash instead of Elasticsearch
#output.logstash:
#  hosts: ["localhost:5044"]

#================================ Processors =====================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

#================================ Logging =====================================
logging.level: info
logging.to_files: true
logging.files:
  path: C:\ProgramData\Metricbeat\Logs
  name: metricbeat
  keepfiles: 7
  permissions: 0644

#============================== X-Pack Monitoring ===============================
monitoring.enabled: true

#================================ HTTP Endpoint ==============================
http.enabled: true
http.host: "0.0.0.0"
http.port: 5066