services:
  # Backend API Service
  - type: web
    name: kartavya-siem-backend
    runtime: python3
    buildCommand: |
      cd backend &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      cd backend &&
      python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    plan: starter
    region: oregon
    branch: main
    rootDir: .
    healthCheckPath: /health
    autoDeploy: true
    
    envVars:
      - key: ENVIRONMENT
        value: demo
      - key: ENABLE_AI
        value: true
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: DEFAULT_SIEM_PLATFORM
        value: dataset
      - key: CORS_ORIGINS
        value: https://kartavya-siem.vercel.app,http://localhost:3000
      
      # These will be set securely in Render dashboard
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

# Database migrations (if needed)
databases: []

# Static sites (none for backend-only service)
static: []
