services:
  - type: web
    name: kartavya-cli
    env: python
    plan: free
    buildCommand: |
      cd cli && pip install -e .
    startCommand: |
      cd cli && python -c "
      from kartavya_cli.main import app
      import uvicorn
      
      # Create a simple web interface for the CLI
      from fastapi import FastAPI, Request
      from fastapi.responses import HTMLResponse
      import subprocess
      import json
      
      web_app = FastAPI(title='Kartavya CLI Web Interface')
      
      @web_app.get('/', response_class=HTMLResponse)
      async def web_interface():
          return '''
          <!DOCTYPE html>
          <html>
          <head>
              <title>Kartavya CLI</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; background: #1a1a1a; color: #fff; }
                  .container { max-width: 1200px; margin: 0 auto; }
                  .terminal { background: #000; color: #00ff00; padding: 20px; border-radius: 8px; font-family: monospace; }
                  .command { margin: 10px 0; }
                  .output { margin-left: 20px; }
                  h1 { color: #4CAF50; }
                  .example { background: #333; padding: 15px; border-radius: 5px; margin: 10px 0; }
              </style>
          </head>
          <body>
              <div class=\"container\">
                  <h1>🔒 Kartavya CLI - Web Interface</h1>
                  <p>Production-ready command line interface for Kartavya SIEM NLP Assistant</p>
                  
                  <h2>Quick Start</h2>
                  <div class=\"example\">
                      <h3>Configuration</h3>
                      <div class=\"terminal\">
                          <div class=\"command\">$ kartavya setup</div>
                          <div class=\"output\">Configure API URL and authentication token</div>
                      </div>
                  </div>
                  
                  <div class=\"example\">
                      <h3>Health Check</h3>
                      <div class=\"terminal\">
                          <div class=\"command\">$ kartavya health</div>
                          <div class=\"output\">✅ API is healthy and accessible</div>
                      </div>
                  </div>
                  
                  <div class=\"example\">
                      <h3>Interactive Chat</h3>
                      <div class=\"terminal\">
                          <div class=\"command\">$ kartavya chat interactive</div>
                          <div class=\"output\">💬 Starting interactive chat session...</div>
                      </div>
                  </div>
                  
                  <h2>API Endpoints</h2>
                  <div class=\"example\">
                      <p><strong>Health Check:</strong> GET /health</p>
                      <p><strong>Execute Command:</strong> POST /execute</p>
                      <p><strong>CLI Status:</strong> GET /status</p>
                  </div>
                  
                  <h2>Environment Variables</h2>
                  <div class=\"example\">
                      <div class=\"terminal\">
                          KARTAVYA_API_URL=https://your-api-endpoint.com<br>
                          KARTAVYA_API_TOKEN=your-secret-token<br>
                          KARTAVYA_OUTPUT_FORMAT=json<br>
                          KARTAVYA_COLOR=true
                      </div>
                  </div>
                  
                  <p><a href=\"https://github.com/kartavya-team/kartavya-cli\" target=\"_blank\">📖 View Documentation</a></p>
              </div>
          </body>
          </html>
          '''
      
      @web_app.get('/health')
      async def health():
          return {'status': 'healthy', 'service': 'kartavya-cli-web'}
      
      @web_app.post('/execute')
      async def execute_command(request: Request):
          try:
              data = await request.json()
              command = data.get('command', 'kartavya --help')
              
              # Execute CLI command
              result = subprocess.run(
                  command.split(), 
                  capture_output=True, 
                  text=True, 
                  timeout=30
              )
              
              return {
                  'success': result.returncode == 0,
                  'stdout': result.stdout,
                  'stderr': result.stderr,
                  'return_code': result.returncode
              }
          except Exception as e:
              return {'success': False, 'error': str(e)}
      
      @web_app.get('/status')
      async def status():
          return {
              'service': 'Kartavya CLI Web Interface',
              'version': '1.0.0',
              'status': 'running'
          }
      
      uvicorn.run(web_app, host='0.0.0.0', port=int(os.environ.get('PORT', 10000)))
      "
    envVars:
      - key: KARTAVYA_API_URL
        value: https://your-kartavya-api.com
      - key: KARTAVYA_COLOR  
        value: "false"
      - key: KARTAVYA_OUTPUT_FORMAT
        value: json
      - key: PORT
        value: "10000"
