services:
  - type: web
    name: kartavya-cli-web
    env: python
    repo: https://github.com/kartavya-team/kartavya-cli.git
    buildCommand: |
      pip install --upgrade pip
      pip install -e .
      pip install fastapi uvicorn jinja2 python-multipart
    startCommand: uvicorn web_interface:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: KARTAVYA_API_BASE_URL
        value: https://api.kartavya.dev
      - key: KARTAVYA_AUTH_API_KEY
        fromSecret: kartavya_api_key
      - key: PYTHONPATH
        value: /opt/render/project/src
    scaling:
      minInstances: 1
      maxInstances: 3
    
  - type: worker
    name: kartavya-cli-worker
    env: python
    repo: https://github.com/kartavya-team/kartavya-cli.git
    buildCommand: |
      pip install --upgrade pip
      pip install -e .
      pip install celery redis
    startCommand: celery -A worker worker --loglevel=info
    envVars:
      - key: KARTAVYA_API_BASE_URL
        value: https://api.kartavya.dev
      - key: KARTAVYA_AUTH_API_KEY
        fromSecret: kartavya_api_key
      - key: REDIS_URL
        fromService:
          type: redis
          name: kartavya-redis
      - key: PYTHONPATH
        value: /opt/render/project/src
    scaling:
      minInstances: 1
      maxInstances: 5

  - type: redis
    name: kartavya-redis
    ipAllowList: []
    plan: starter

databases:
  - name: kartavya-cli-db
    databaseName: kartavya_cli
    user: kartavya_user
    plan: starter

# Optional: Static site for documentation
  - type: static
    name: kartavya-cli-docs
    buildCommand: |
      pip install mkdocs mkdocs-material
      mkdocs build
    publishPath: ./site
    envVars:
      - key: SITE_URL
        value: https://kartavya-cli-docs.onrender.com
