# Index-aware field preferences per dataset (stub; extend as needed)
# This file is optional and read by the query builder (planned integration).
# Use it to prioritize field names based on your index semantics.

windows:
  username:
    - winlog.event_data.TargetUserName
    - user.name
    - winlog.user.name
  source_ip:
    - source.ip
    - winlog.event_data.IpAddress
  event_id:
    - winlog.event_id
    - event.code
  hostname:
    - winlog.computer_name
    - host.name

linux:
  username:
    - system.auth.user
    - user.name
  source_ip:
    - source.ip
  hostname:
    - host.name

network:
  source_ip:
    - source.ip
  destination_ip:
    - destination.ip
  destination_port:
    - destination.port
  protocol:
    - network.protocol
